// This would typically come from a database, but for our demo we'll use static data
export const animeData = {
  "solo-leveling": {
    id: "solo-leveling",
    title: "Solo Leveling Season 2: Arise from the Shadow",
    japaneseTitle: "ソロレベリング シーズン2",
    image: "https://ext.same-assets.com/1515222727/467283363.jpeg",
    bannerImage: "https://ext.same-assets.com/1515222727/467283363.jpeg",
    episodes: 13,
    currentEpisode: 12,
    status: "Ongoing",
    type: "TV",
    year: 2025,
    season: "Winter",
    duration: "24m",
    rating: "HD",
    score: "9.8",
    studios: ["A-1 Pictures"],
    genres: ["Action", "Adventure", "Fantasy", "Supernatural"],
    description:
      "Sung Jin-Woo, dubbed the weakest hunter of all mankind, grows stronger by the day with the supernatural powers he has gained. However, keeping his skills hidden becomes more difficult as dungeon-related incidents pile up around him. When Jin-Woo and a few other low-ranked hunters are the only survivors of a dungeon that turns out to be a bigger challenge than initially expected, he draws attention once again, and hunter guilds take an increased interest in him. Meanwhile, a strange hunter who has been lost for ten years returns with a dire warning about an upcoming catastrophic event. As the calamity looms closer, Jin-Woo must continue leveling up to make sure nothing stops him from reaching his ultimate goal—saving the life of his mother.",
    episodeList: Array.from({ length: 13 }, (_, i) => ({
      number: i + 1,
      title: `Episode ${i + 1}`,
      thumbnail: "https://ext.same-assets.com/1515222727/467283363.jpeg",
      date: new Date(2025, 0, 5 + i * 7).toLocaleDateString(),
      duration: "24m",
    })),
    characters: [
      {
        name: "Sung Jin-Woo",
        image: "https://ext.same-assets.com/1515222727/3156069097.jpeg",
        role: "Main",
      },
      {
        name: "Cha Hae-In",
        image: "https://ext.same-assets.com/1515222727/847111745.jpeg",
        role: "Main",
      },
      {
        name: "Sung Jin-Ah",
        image: "https://ext.same-assets.com/1515222727/771550143.jpeg",
        role: "Supporting",
      },
    ],
    similarAnime: [
      {
        id: "dragon-ball",
        title: "Dragon Ball Daima",
        image: "https://ext.same-assets.com/1515222727/771550143.jpeg",
      },
      {
        id: "one-piece",
        title: "One Piece",
        image: "https://ext.same-assets.com/1515222727/847111745.jpeg",
      },
      {
        id: "100-girlfriends",
        title: "The 100 Girlfriends Who Really, Really, Really, Really, Really Love You Season 2",
        image: "https://ext.same-assets.com/1515222727/467283363.jpeg",
      },
    ],
  },
  "one-piece": {
    id: "one-piece",
    title: "One Piece",
    japaneseTitle: "ワンピース",
    image: "https://ext.same-assets.com/1515222727/847111745.jpeg",
    bannerImage: "https://ext.same-assets.com/1515222727/847111745.jpeg",
    episodes: 1124,
    currentEpisode: 1122,
    status: "Ongoing",
    type: "TV",
    year: 1999,
    season: "Fall",
    duration: "24m",
    rating: "HD",
    score: "9.5",
    studios: ["Toei Animation"],
    genres: ["Action", "Adventure", "Comedy", "Drama", "Fantasy", "Shounen"],
    description:
      "Gold Roger was known as the 'Pirate King,' the strongest and most infamous being to have sailed the Grand Line. The capture and execution of Roger by the World Government brought a change throughout the world. His last words before his death revealed the existence of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece—which promises an unlimited amount of riches and fame—and quite possibly the pinnacle of glory and the title of the Pirate King. Enter Monkey D. Luffy, a 17-year-old boy who defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate ransacking villages for fun, Luffy's reason for being a pirate is one of pure wonder: the thought of an exciting adventure that leads him to intriguing people and ultimately, the promised treasure. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach the most coveted of all fortunes—One Piece.",
    episodeList: Array.from({ length: 10 }, (_, i) => ({
      number: 1113 + i,
      title: `Episode ${1113 + i}`,
      thumbnail: "https://ext.same-assets.com/1515222727/847111745.jpeg",
      date: new Date(2023, 10, 5 + i * 7).toLocaleDateString(),
      duration: "24m",
    })),
    characters: [
      {
        name: "Monkey D. Luffy",
        image: "https://ext.same-assets.com/1515222727/847111745.jpeg",
        role: "Main",
      },
      {
        name: "Roronoa Zoro",
        image: "https://ext.same-assets.com/1515222727/3156069097.jpeg",
        role: "Main",
      },
      {
        name: "Nami",
        image: "https://ext.same-assets.com/1515222727/771550143.jpeg",
        role: "Main",
      },
    ],
    similarAnime: [
      {
        id: "dragon-ball",
        title: "Dragon Ball Daima",
        image: "https://ext.same-assets.com/1515222727/771550143.jpeg",
      },
      {
        id: "solo-leveling",
        title: "Solo Leveling Season 2: Arise from the Shadow",
        image: "https://ext.same-assets.com/1515222727/467283363.jpeg",
      },
      {
        id: "blue-box",
        title: "Blue Box",
        image: "https://ext.same-assets.com/1515222727/3156069097.jpeg",
      },
    ],
  },
  "dragon-ball": {
    id: "dragon-ball",
    title: "Dragon Ball Daima",
    japaneseTitle: "ドラゴンボール大魔",
    image: "https://ext.same-assets.com/1515222727/771550143.jpeg",
    bannerImage: "https://ext.same-assets.com/1515222727/771550143.jpeg",
    episodes: 20,
    currentEpisode: 13,
    status: "Ongoing",
    type: "TV",
    year: 2024,
    season: "Fall",
    duration: "24m",
    rating: "HD",
    score: "9.2",
    studios: ["Toei Animation"],
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Martial Arts", "Shounen"],
    description:
      "After saving the world from the destructive might of Majin Buu, Gokuu Son and his allies look forward to a well-earned rest. However, unbeknownst to them, their battle was recorded and observed by Gomah, an evil being who assumes the title of King in the Demon Realm, filling the void left behind with the death of former ruler Dabura. At Gomah's side is Degesu, the younger brother of Higashi no Kaioshin, a being who lords over the universe. Jealous of his brother's power, Degesu works alongside Gomah to steal Earth's Dragon Balls and preemptively subdue any potential future enemies. Calling upon the power of the legendary dragon Shenron, Gomah wishes for Gokuu and his friends to be reverted into children, intending to rob them of the limitless power that defeated Buu.",
    episodeList: Array.from({ length: 13 }, (_, i) => ({
      number: i + 1,
      title: `Episode ${i + 1}`,
      thumbnail: "https://ext.same-assets.com/1515222727/771550143.jpeg",
      date: new Date(2024, 9, 11 + i * 7).toLocaleDateString(),
      duration: "24m",
    })),
    characters: [
      {
        name: "Son Goku",
        image: "https://ext.same-assets.com/1515222727/771550143.jpeg",
        role: "Main",
      },
      {
        name: "Vegeta",
        image: "https://ext.same-assets.com/1515222727/3156069097.jpeg",
        role: "Main",
      },
      {
        name: "Bulma",
        image: "https://ext.same-assets.com/1515222727/467283363.jpeg",
        role: "Supporting",
      },
    ],
    similarAnime: [
      {
        id: "one-piece",
        title: "One Piece",
        image: "https://ext.same-assets.com/1515222727/847111745.jpeg",
      },
      {
        id: "solo-leveling",
        title: "Solo Leveling Season 2: Arise from the Shadow",
        image: "https://ext.same-assets.com/1515222727/467283363.jpeg",
      },
      {
        id: "blue-box",
        title: "Blue Box",
        image: "https://ext.same-assets.com/1515222727/3156069097.jpeg",
      },
    ],
  },
  // Add more anime data for movies here
  "sao-progressive": {
    id: "sao-progressive",
    title: "Sword Art Online Progressive: Scherzo of Deep Night",
    japaneseTitle: "ソードアート・オンライン プログレッシブ 冥き夕闇のスケルツォ",
    image: "https://ext.same-assets.com/1515222727/3156069097.jpeg",
    bannerImage: "https://ext.same-assets.com/1515222727/3156069097.jpeg",
    episodes: 1,
    currentEpisode: 1,
    status: "Completed",
    type: "Movie",
    year: 2023,
    season: "Winter",
    duration: "1h 41m",
    rating: "HD",
    score: "7.4",
    studios: ["A-1 Pictures"],
    genres: ["Action", "Adventure", "Fantasy", "Romance"],
    description:
      "Following the events on the first floor of Aincrad, Asuna and Kirito continue their progress through the death game. Kirito is determined to prioritize Asuna's safety, while Asuna strives to define the nature of their relationship. As they tackle the challenges of the fourth floor, they soon witness something unexpected: NPCs disappearing without a trace. Meanwhile, a murder occurs within the safe zone, enhancing the anxiety of the trapped players. Though safe zones are supposed to protect players from harm, the unthinkable has happened, spreading fear and mistrust.",
    episodeList: Array.from({ length: 1 }, (_, i) => ({
      number: i + 1,
      title: "Full Movie",
      thumbnail: "https://ext.same-assets.com/1515222727/3156069097.jpeg",
      date: new Date(2023, 0, 5).toLocaleDateString(),
      duration: "1h 41m",
    })),
    characters: [
      {
        name: "Kirito",
        image: "https://ext.same-assets.com/1515222727/771550143.jpeg",
        role: "Main",
      },
      {
        name: "Asuna",
        image: "https://ext.same-assets.com/1515222727/847111745.jpeg",
        role: "Main",
      },
    ],
    similarAnime: [
      {
        id: "your-name",
        title: "Kimi no Na wa (Your Name)",
        image: "https://ext.same-assets.com/1515222727/467283363.jpeg",
      },
      {
        id: "suzume",
        title: "Suzume no Tojimari",
        image: "https://ext.same-assets.com/1515222727/847111745.jpeg",
      },
    ],
  },
  "your-name": {
    id: "your-name",
    title: "Kimi no Na wa (Your Name)",
    japaneseTitle: "君の名は。",
    image: "https://ext.same-assets.com/1515222727/467283363.jpeg",
    bannerImage: "https://ext.same-assets.com/1515222727/467283363.jpeg",
    episodes: 1,
    currentEpisode: 1,
    status: "Completed",
    type: "Movie",
    year: 2016,
    season: "Summer",
    duration: "1h 47m",
    rating: "HD",
    score: "9.2",
    studios: ["CoMix Wave Films"],
    genres: ["Drama", "Romance", "Supernatural"],
    description:
      "From director Makoto Shinkai, the innovative mind behind Voices of a Distant Star and 5 Centimeters Per Second, comes a beautiful masterpiece about time, the thread of fate, and the hearts of two young souls. Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture. One day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki's body! Elsewhere, Taki finds himself living Mitsuha's life in the humble countryside. In pursuit of an answer to this strange phenomenon, they begin to search for one another.",
    episodeList: Array.from({ length: 1 }, (_, i) => ({
      number: i + 1,
      title: "Full Movie",
      thumbnail: "https://ext.same-assets.com/1515222727/467283363.jpeg",
      date: new Date(2016, 7, 26).toLocaleDateString(),
      duration: "1h 47m",
    })),
    characters: [
      {
        name: "Taki Tachibana",
        image: "https://ext.same-assets.com/1515222727/771550143.jpeg",
        role: "Main",
      },
      {
        name: "Mitsuha Miyamizu",
        image: "https://ext.same-assets.com/1515222727/847111745.jpeg",
        role: "Main",
      },
    ],
    similarAnime: [
      {
        id: "weathering-with-you",
        title: "Tenki no Ko (Weathering With You)",
        image: "https://ext.same-assets.com/1515222727/467283363.jpeg",
      },
      {
        id: "suzume",
        title: "Suzume no Tojimari",
        image: "https://ext.same-assets.com/1515222727/847111745.jpeg",
      },
    ],
  },
};
